apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: c2c-marketplace
  labels:
    tier: app 
type: Opaque
stringData:  
  SECRET_KEY: 'django-insecure-1zg=3_&6sb4rel!x9$52sx_hlx#%))+k+xyrczu!3kbgcczlr^'
data:
  DB_PASSWORD: YWFhYTAwMDA=