apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: c2c-marketplace
  labels:
    tier: pgadmin
type: Opaque
data:
  POSTGRES_PASSWORD: YWFhYTAwMDA=
  PGADMIN_DEFAULT_PASSWORD: YWFhYTAwMDA=