apiVersion: v1
kind: Service
metadata:
  labels:
    tier: pgadmin
  namespace: c2c-marketplace
  name: pgadmin-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    tier: pgadmin
  type: ClusterIP
status:
  loadBalancer: {}
