apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: c2c-marketplace
  # labels:
  #   tier: db
data:
  POSTGRES_HOST: "db-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ahmed
  POSTGRES_DB: C2CMarketplace