apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: c2c-marketplace
  labels:
    tier: db
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/postgresql/data